--T2
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET TRANSACTION ISOLATION LEVEL READ COMMITTED --solution
BEGIN TRANSACTION
SELECT * FROM Fan
WAITFOR DELAY '00:00:15'
SELECT * FROM Fan
COMMIT TRAN