

WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE Fan SET fan_age = 21 WHERE fan_id=100
WAITFOR DELAY '00:00:05'
COMMIT TRAN

--ALTER DATABASE Music_Production_Company SET ALLOW_SNAPSHOT_ISOLATION_OFF
--UPDATE Fan SET fan_age = 20 WHERE fan_id = 100
--SELECT * FROM Fan